name: auto-import
on:
  workflow_dispatch:

jobs:
  fetch_files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Download files from FTP server
        env:
          FTP_SERVER: ${{ secrets.FTP_SERVER }}
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
          XML_FILE_PATH: ${{ secrets.XML_FILE_PATH }}
        run: python download_file_from_ftp.py

  prepare_data:
    needs: fetch_files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate CSV file
        run: python auto-import-script.py

  import_data:
    needs: prepare_data
    container: gradle:jdk11
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Install PostgreSQL client
        run: |
          apt-get update
          apt-get install -y postgresql-client

      - name: Copy data into PostgreSQL
        env:
          DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
        run: |
          psql "postgres://postgres:${DATABASE_PASSWORD}@aws-0-us-west-1.pooler.supabase.com:5432/postgres" -c "\COPY public.articles(content, title) FROM 'temp_data.csv' WITH (FORMAT csv);"

  cleanup:
    needs: import_data
    runs-on: ubuntu-latest
    steps:
      - name: Remove temporary files
        run: |
          rm -rf ./data
          rm -f temp_data.csv