name: auto-import
on:
  schedule:
    # Runs every 5 minutes
    - cron: '*/5 * * * *'
  workflow_dispatch:
  
jobs:
  build:
    container: gradle:jdk11
    runs-on: ubuntu-latest
    steps:
      - run: |
          apt-get update
          apt-get install --yes --no-install-recommends postgresql-client
          psql -h aws-0-us-west-1.pooler.supabase.com -p 5432 -d postgres -U postgres.fbsstbcuoxstmqjgqdwy -c "\COPY movies FROM '../temp_data.csv';"
  import_data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
      env:
        SUPABASE_ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        SUPABASE_DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        PROJECT_ID: ${{ secrets.PROJECT_ID}}
