name: auto-import
on:
  schedule:
    # Runs every 5 minutes
    - cron: '*/5 * * * *'
  workflow_dispatch:
  
jobs:
  build:
    container: gradle:jdk11
    runs-on: ubuntu-latest
    steps:
      - run: |
          apt-get update
          apt-get install --yes --no-install-recommends postgresql-client
  import_data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
      env:
        SUPABASE_ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        SUPABASE_DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        PROJECT_ID: ${{ secrets.PROJECT_ID}}
